### Imports

In [16]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
# import plotly.express as px
# from plotly import graph_objects as go

import matplotlib
import sklearn
# import plotly

# from IPython.display import display

print("package版本信息：")
print("numpy:      ", np.__version__)
print("pandas:     ", pd.__version__)
print("matplotlib: ", matplotlib.__version__)
print("sklearn:    ", sklearn.__version__)
print("seaborn:    ", sns.__version__)
# print("plotly:     ", plotly.__version__)

package版本信息：
numpy:       2.2.6
pandas:      2.2.3
matplotlib:  3.10.3
sklearn:     1.6.1
seaborn:     0.13.2

In [27]:
# 回归数据集
from sklearn.datasets import fetch_california_housing
# 分类数据集
from sklearn.datasets import load_breast_cancer

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline

from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.tree import DecisionTreeRegressor, DecisionTreeClassifier
from sklearn.svm import SVR, SVC

#from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
from sklearn.ensemble import GradientBoostingRegressor, GradientBoostingClassifier
from sklearn.ensemble import  HistGradientBoostingRegressor, HistGradientBoostingClassifier
from sklearn.ensemble import VotingRegressor, VotingClassifier
from sklearn.ensemble import StackingRegressor, StackingClassifier

# 数据集

使用的数据集如下：

## 回归问题

In [37]:
housing_data = fetch_california_housing(as_frame=True)

In [38]:
print(housing_data.keys())

dict_keys(['data', 'target', 'frame', 'target_names', 'feature_names', 'DESCR'])

In [39]:
print('feature_names: ', housing_data.feature_names)
print('target_names: ', housing_data.target_names)

feature_names:  ['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup', 'Latitude', 'Longitude']
target_names:  ['MedHouseVal']

In [40]:
print(housing_data.DESCR)

.. _california_housing_dataset:

California Housing dataset
--------------------------

**Data Set Characteristics:**

:Number of Instances: 20640

:Number of Attributes: 8 numeric, predictive attributes and the target

:Attribute Information:
    - MedInc        median income in block group
    - HouseAge      median house age in block group
    - AveRooms      average number of rooms per household
    - AveBedrms     average number of bedrooms per household
    - Population    block group population
    - AveOccup      average number of household members
    - Latitude      block group latitude
    - Longitude     block group longitude

:Missing Attribute Values: None

This dataset was obtained from the StatLib repository.
https://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.html

The target variable is the median house value for California districts,
expressed in hundreds of thousands of dollars ($100,000).

This dataset was derived from the 1990 U.S. census, using one row per census
block group. A block group is the smallest geographical unit for which the U.S.
Census Bureau publishes sample data (a block group typically has a population
of 600 to 3,000 people).

A household is a group of people residing within a home. Since the average
number of rooms and bedrooms in this dataset are provided per household, these
columns may take surprisingly large values for block groups with few households
and many empty houses, such as vacation resorts.

It can be downloaded/loaded using the
:func:`sklearn.datasets.fetch_california_housing` function.

.. rubric:: References

- Pace, R. Kelley and Ronald Barry, Sparse Spatial Autoregressions,
  Statistics and Probability Letters, 33 (1997) 291-297

In [41]:
print(housing_data.data.shape)

(20640, 8)

In [42]:
housing_data.frame.head(5)

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422

+ 划分训练&验证集和测试集

In [43]:
housing_X_train, housing_X_test, housing_y_train, housing_y_test = train_test_split(housing_data.data, housing_data.target, test_size=0.2, random_state=32)

In [44]:
housing_X_train.head(5)

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
1032,3.1250,23.0,6.375796,1.242038,369.0,2.350318,38.51,-120.80
10807,4.4211,35.0,5.305970,1.027363,1473.0,3.664179,33.65,-117.93
87,0.7600,10.0,2.651515,1.054545,546.0,1.654545,37.81,-122.27
4395,2.6178,52.0,3.304290,1.036193,2328.0,3.120643,34.08,-118.28
19053,3.2937,33.0,5.317647,1.067647,824.0,2.423529,38.16,-121.69

In [45]:
housing_y_train.head()

1032     0.964
10807    2.152
87       1.625
4395     2.031
19053    0.964
Name: MedHouseVal, dtype: float64

## 分类问题

下面是一个二分类的数据集。

In [3]:
cancer_data = load_breast_cancer(as_frame=True)

In [4]:
print(cancer_data.keys())

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [5]:
print('feature_names: ', cancer_data.feature_names)
print('target_names: ',cancer_data.target_names)

feature_names:  ['mean radius' 'mean texture' 'mean perimeter' 'mean area'
 'mean smoothness' 'mean compactness' 'mean concavity'
 'mean concave points' 'mean symmetry' 'mean fractal dimension'
 'radius error' 'texture error' 'perimeter error' 'area error'
 'smoothness error' 'compactness error' 'concavity error'
 'concave points error' 'symmetry error' 'fractal dimension error'
 'worst radius' 'worst texture' 'worst perimeter' 'worst area'
 'worst smoothness' 'worst compactness' 'worst concavity'
 'worst concave points' 'worst symmetry' 'worst fractal dimension']
target_names:  ['malignant' 'benign']

In [8]:
print(cancer_data.DESCR)

.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

:Number of Instances: 569

:Number of Attributes: 30 numeric, predictive attributes and the class

:Attribute Information:
    - radius (mean of distances from center to points on the perimeter)
    - texture (standard deviation of gray-scale values)
    - perimeter
    - area
    - smoothness (local variation in radius lengths)
    - compactness (perimeter^2 / area - 1.0)
    - concavity (severity of concave portions of the contour)
    - concave points (number of concave portions of the contour)
    - symmetry
    - fractal dimension ("coastline approximation" - 1)

    The mean, standard error, and "worst" or largest (mean of the three
    worst/largest values) of these features were computed for each image,
    resulting in 30 features.  For instance, field 0 is Mean Radius, field
    10 is Radius SE, field 20 is Worst Radius.

    - class:
            - WDBC-Malignant
            - WDBC-Benign

:Summary Statistics:

===================================== ====== ======
                                        Min    Max
===================================== ====== ======
radius (mean):                        6.981  28.11
texture (mean):                       9.71   39.28
perimeter (mean):                     43.79  188.5
area (mean):                          143.5  2501.0
smoothness (mean):                    0.053  0.163
compactness (mean):                   0.019  0.345
concavity (mean):                     0.0    0.427
concave points (mean):                0.0    0.201
symmetry (mean):                      0.106  0.304
fractal dimension (mean):             0.05   0.097
radius (standard error):              0.112  2.873
texture (standard error):             0.36   4.885
perimeter (standard error):           0.757  21.98
area (standard error):                6.802  542.2
smoothness (standard error):          0.002  0.031
compactness (standard error):         0.002  0.135
concavity (standard error):           0.0    0.396
concave points (standard error):      0.0    0.053
symmetry (standard error):            0.008  0.079
fractal dimension (standard error):   0.001  0.03
radius (worst):                       7.93   36.04
texture (worst):                      12.02  49.54
perimeter (worst):                    50.41  251.2
area (worst):                         185.2  4254.0
smoothness (worst):                   0.071  0.223
compactness (worst):                  0.027  1.058
concavity (worst):                    0.0    1.252
concave points (worst):               0.0    0.291
symmetry (worst):                     0.156  0.664
fractal dimension (worst):            0.055  0.208
===================================== ====== ======

:Missing Attribute Values: None

:Class Distribution: 212 - Malignant, 357 - Benign

:Creator:  Dr. William H. Wolberg, W. Nick Street, Olvi L. Mangasarian

:Donor: Nick Street

:Date: November, 1995

This is a copy of UCI ML Breast Cancer Wisconsin (Diagnostic) datasets.
https://goo.gl/U2Uwz2

Features are computed from a digitized image of a fine needle
aspirate (FNA) of a breast mass.  They describe
characteristics of the cell nuclei present in the image.

Separating plane described above was obtained using
Multisurface Method-Tree (MSM-T) [K. P. Bennett, "Decision Tree
Construction Via Linear Programming." Proceedings of the 4th
Midwest Artificial Intelligence and Cognitive Science Society,
pp. 97-101, 1992], a classification method which uses linear
programming to construct a decision tree.  Relevant features
were selected using an exhaustive search in the space of 1-4
features and 1-3 separating planes.

The actual linear program used to obtain the separating plane
in the 3-dimensional space is that described in:
[K. P. Bennett and O. L. Mangasarian: "Robust Linear
Programming Discrimination of Two Linearly Inseparable Sets",
Optimization Methods and Software 1, 1992, 23-34].

This database is also available through the UW CS ftp server:

ftp ftp.cs.wisc.edu
cd math-prog/cpo-dataset/machine-learn/WDBC/

.. dropdown:: References

  - W.N. Street, W.H. Wolberg and O.L. Mangasarian. Nuclear feature extraction
    for breast tumor diagnosis. IS&T/SPIE 1993 International Symposium on
    Electronic Imaging: Science and Technology, volume 1905, pages 861-870,
    San Jose, CA, 1993.
  - O.L. Mangasarian, W.N. Street and W.H. Wolberg. Breast cancer diagnosis and
    prognosis via linear programming. Operations Research, 43(4), pages 570-577,
    July-August 1995.
  - W.H. Wolberg, W.N. Street, and O.L. Mangasarian. Machine learning techniques
    to diagnose breast cancer from fine-needle aspirates. Cancer Letters 77 (1994)
    163-171.

In [6]:
print(cancer_data.data.shape)

(569, 30)

In [7]:
cancer_data.frame.head(5)

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,0
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,0
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,0
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,0
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,0

In [9]:
cancer_data.target.head(5)

0    0
1    0
2    0
3    0
4    0
Name: target, dtype: int64

In [11]:
cancer_data.target.nunique()

2

In [14]:
cancer_data.target.value_counts()

target
1    357
0    212
Name: count, dtype: int64

+ 划分训练&验证集和测试集

In [24]:
cancer_X_train, cancer_X_test, cancer_y_train, cancer_y_test = train_test_split(cancer_data.data, cancer_data.target, test_size=0.2, stratify=cancer_data.target, random_state=32)

In [25]:
print(cancer_X_train.shape)
print(cancer_X_test.shape)

(455, 30)
(114, 30)

# 介绍

整理 `sklearn.ensemble` 模块里提供的集成学习模型，该模块里主要分为如下几类集成模型：
+ Bagging
+ Boosting
+ 结合策略
+ 其他

---
# Bagging

提供了并行集成相关的模型。

## 基础bagging模型

```python
# 回归问题
BaggingRegressor(
    estimator=None, n_estimators=10, *, 
    max_samples=1.0, max_features=1.0, 
    bootstrap=True, bootstrap_features=False, oob_score=False, 
    warm_start=False, n_jobs=None, random_state=None, verbose=0
)

# 分类问题
BaggingClassifier(
    estimator=None, n_estimators=10, *, 
    max_samples=1.0, max_features=1.0, 
    bootstrap=True, bootstrap_features=False, oob_score=False, 
    warm_start=False, n_jobs=None, random_state=None, verbose=0
)
```

## Random Forests

sklearn提供的API如下：
```python
# 回归问题
RandomForestRegressor(
    n_estimators=100, *, 
    criterion='squared_error', 
    max_depth=None, min_samples_split=2, min_samples_leaf=1, min_weight_fraction_leaf=0.0, 
    max_features=1.0, max_leaf_nodes=None, min_impurity_decrease=0.0, 
    bootstrap=True, oob_score=False, n_jobs=None, random_state=None, 
    verbose=0, warm_start=False, ccp_alpha=0.0, max_samples=None, monotonic_cst=None
)

# 分类问题
RandomForestClassifier(
    n_estimators=100, *, 
    criterion='gini', 
    max_depth=None, min_samples_split=2, min_samples_leaf=1, min_weight_fraction_leaf=0.0, 
    max_features='sqrt', max_leaf_nodes=None, min_impurity_decrease=0.0, 
    bootstrap=True, oob_score=False, n_jobs=None, random_state=None, 
    verbose=0, warm_start=False, 
    class_weight=None,   # 独有参数
    ccp_alpha=0.0, max_samples=None, monotonic_cst=None
)
```

此外，sklearn还提供了一个基于随机森林的无监督密度估计方法。
```python
RandomTreesEmbedding(
    n_estimators=100, *, 
    max_depth=5, min_samples_split=2, min_samples_leaf=1, min_weight_fraction_leaf=0.0, 
    max_leaf_nodes=None, min_impurity_decrease=0.0, sparse_output=True, 
    n_jobs=None, random_state=None, verbose=0, warm_start=False
)
```

## Extremely Randomized Trees

---
# Boosting

提供了串行集成相关的模型。

## AdaBoost

sklearn提供的API如下：
```python
# 回归问题
AdaBoostRegressor(estimator=None, *, n_estimators=50, learning_rate=1.0, loss='linear', random_state=None)

# 分类问题
AdaBoostClassifier(estimator=None, *, n_estimators=50, learning_rate=1.0, algorithm='SAMME.R', random_state=None)
```

---
## GBDT - KEY

sklearn提供了两个版本的GBDT实现，普通版本和快速版本。

### 普通版本
```python
# 回归树 API
GradientBoostingRegressor(*, 
    loss='squared_error',
    learning_rate=0.1, n_estimators=100, subsample=1.0, criterion='friedman_mse', 
    min_samples_split=2, min_samples_leaf=1, min_weight_fraction_leaf=0.0, max_depth=3, min_impurity_decrease=0.0,
    init=None, random_state=None, max_features=None, 
    alpha=0.9,   # 回归树独有
    verbose=0, max_leaf_nodes=None, warm_start=False, validation_fraction=0.1,
    n_iter_no_change=None, tol=0.0001, ccp_alpha=0.0
)

# 分类树 API
GradientBoostingClassifier(*,
    loss='log_loss',
    learning_rate=0.1, n_estimators=100, subsample=1.0, criterion='friedman_mse', 
    min_samples_split=2, min_samples_leaf=1, min_weight_fraction_leaf=0.0, max_depth=3, min_impurity_decrease=0.0,
    init=None, random_state=None, max_features=None, 
    verbose=0, max_leaf_nodes=None, warm_start=False, validation_fraction=0.1, 
    n_iter_no_change=None, tol=0.0001, ccp_alpha=0.0
)
```

对比可以看出，两者的参数里，除了 `loss` 不一样，几乎都一致，除了回归树多了一个`alpha`参数，因此下面就一起介绍了。

#### 参数

GBDT普通版本的参数可以分为如下 4 类：

+ 训练过程

| 参数                                   | 含义                     | 影响力 | 说明                                    |
| -------------------------------------- | ------------------------ | ------ | --------------------------------------- |
| loss                                   | 损失函数                 | ⭐⭐⭐    | 可选值见下面说明                        |
| <font color="red">n_estimators</font>  | 基函数个数               | ⭐⭐⭐⭐⭐  | int，默认100                            |
| <font color="red">learning_rate</font> | 学习率                   | ⭐⭐⭐⭐⭐  | float，默认0.1                          |
| <font color="red">max_features</font>  | 基函数训练时使用的特征数 | ⭐⭐⭐⭐⭐  | 默认None表示使用全部。有多种方式配置。  |
| subsample                              | 基函数训练时的采样比例   | ⭐⭐⭐    | float，必须在 $(0.0,1.0])$之间，默认1.0 |
| init                                   | 初始值设置               | ⭐⭐      | 默认None                                |
| random_state                           | 随机数状态               | ⭐      | 默认None                                |
| alpha                                  |                          | ⭐      |                                         |


+ 基函数参数

| 参数                     | 含义                           | 影响力 | 说明                                            |
| ------------------------ | ------------------------------ | ------ | ----------------------------------------------- |
| criterion                | CART分裂时的准则               | ⭐⭐     | 可选值为`friedman_mse`（默认），`squared_error` |
| min_samples_split        | 节点分裂时需要包含的最小样本数 | ⭐⭐     | int表示个数（默认2），float表示比例             |
| min_samples_leaf         | 叶子节点的最小样本数           | ⭐⭐     | int表示个数，float表示比例                      |
| max_depth                | 树的最大深度                   | ⭐⭐     | int，默认3                                      |
| min_impurity_decrease    | 节点分裂时的最小不纯度增益     | ⭐⭐     | float，默认0.                                   |
| max_leaf_nodes           | 叶子结点的最大个数             | ⭐⭐     | int，默认None，表示无限制                       |
| min_weight_fraction_leaf |                                |        |                                                 |


+ 提前停止

| 参数                | 含义                                                   | 说明                              |
| ------------------- | ------------------------------------------------------ | --------------------------------- |
| validation_fraction | 用于计算提前停止的验证集比例                           | float，默认0.1                    |
| n_iter_no_change    | 提前停止的轮数，表示多少轮验证集无变化之后，就提前停止 | int，默认None，表示不启用提前停止 |
| tol                 | 提前停止判断的loss变化值                               | float，默认1e-4                   |

+ 其他

| 参数       | 含义 | 说明 |
| ---------- | ---- | ---- |
| verbose    |      |      |
| ccp_alpha  |      |      |
| warm_start |      |      |

#### 属性和方法

### 快速版本
```python
# 回归树 API
HistGradientBoostingRegressor(
    loss='squared_error', 
    *, quantile=None, 
    learning_rate=0.1, max_iter=100, max_leaf_nodes=31, max_depth=None, 
    min_samples_leaf=20, l2_regularization=0.0, max_features=1.0, max_bins=255,
    categorical_features='warn', monotonic_cst=None, interaction_cst=None, warm_start=False, 
    early_stopping='auto', scoring='loss', validation_fraction=0.1, 
    n_iter_no_change=10, tol=1e-07, verbose=0, random_state=None
)

# 分类树 API
HistGradientBoostingClassifier(
    loss='log_loss', 
    *, 
    learning_rate=0.1, max_iter=100, max_leaf_nodes=31, max_depth=None, 
    min_samples_leaf=20, l2_regularization=0.0, max_features=1.0, max_bins=255, 
    categorical_features='warn', monotonic_cst=None, interaction_cst=None, warm_start=False, 
    early_stopping='auto', scoring='loss', validation_fraction=0.1, 
    n_iter_no_change=10, tol=1e-07, verbose=0, random_state=None, 
    class_weight=None  # 分类树独有
)
```

对比可以看出，快速版本的回归和分类API参数差异也不大。

但是快速版本相比普通版本，提供了一些其他的支持。

#### 参数

快速版本特有的参数如下：

| 参数                 | 含义                                   | 影响力 | 说明         |
| -------------------- | -------------------------------------- | ------ | ------------ |
| max_iter             | 最大迭代次数，相当于`n_estimators`参数 |        | int，默认100 |
| l2_regularization    | L2正则项                               |        |              |
| max_bins             | 最大分箱数                             |        |              |
| categorical_features | 处理分类特征                           |        |              |
| monotonic_cst        |                                        |        |              |
| interaction_cst      |                                        |        |              |
| early_stopping       | 提前停止策略                           |        |              |
| scoring              | 提前停止的评价指标                     |        |              |
| quantile             | `loss='quantile'`时使用                |        |              |

#### 属性和方法

### 损失函数

sklearn里GBDT支持的损失函数如下.

#### 回归问题
`GradientBoostingRegressor`
+ squared_error，默认值
+ absolute_error
+ quantile
+ huber

`HistGradientBoostingRegressor`
+ squared_error
+ absolute_error
+ quantile
+ gamma
+ poisson

各损失函数详情如下：

+ **squared_error——平方误差**

$$
L = \sum{(y_i - H(x_i))^2}
$$

+ **absolute_error——绝对误差**

$$
L = \sum{|y_i - H(x_i)|}
$$


+ **quantile**

$$
L = \sum{l(y_i,H(x_i))}
$$

其中
$$
l = \begin{split} 
\begin{cases}
    \alpha (y_i - H(x_i)), & y_i - H(x_i) > 0 \\
    0,    & y_i - H(x_i) = 0 \\
    (1-\alpha) (y_i - H(x_i)), & y_i - H(x_i) < 0
\end{cases}\end{split}, \space \space \alpha \in (0, 1)
$$


+ **huber——合页误差**

$$
L = \sum{l(y_i,H(x_i))}
$$

其中
$$
l = \begin{split} 
\begin{cases}\frac{1}{2}(y_i - H(x_i))^2, & |y_i - H(x_i)|\leq\alpha \\
\alpha(|y_i - H(x_i)|-\frac{\alpha}{2}),& |y_i - H(x_i)|>\alpha \end{cases}\end{split}, \space \space \alpha \in (0, 1)
$$

其中$\alpha$是需要我们自己设置的超参数，由参数`alpha`控制。在huber损失中，alpha是阈值，在quantile损失中，alpha用于辅助计算损失函数的输出结果，默认为0.9

#### 分类问题
`GradientBoostingClassifier`
+ log_loss
+ exponential

`HistGradientBoostingClassifier`
+ log_loss, 只支持这一种


对任意样本$i$而言，$y_i$为真实标签，$\hat{y_i}$为预测标签，$H(x_i)$为集成算法输出结果，$p(x_i)$为基于$H(x_i)$和sigmoid/softmax函数计算的概率值。
那么各损失函数详情如下：

+ **log_loss——对数几率**，也叫交叉熵损失

**二分类交叉熵损失**
$$
L = -\left( y\log p(x) + (1 - y)\log(1 - p(x)) \right)
$$
注意，log当中输入的一定是概率值。对于逻辑回归来说，概率就是算法的输出，因此我们可以认为逻辑回归中$p = H(x)$，但对于GBDT来说，$p(x_i) = Sigmoid(H(x_i))$，这一点一定要注意。


**多分类交叉熵损失**，总共有K个类别

$$
L = -\sum_{k=1}^Ky^*_k\log(P^k(x))
$$

其中，$P^k(x)$是概率值，对于多分类GBDT来说，$p^k(x) = Softmax(H^k(x))$，$y^*$是由真实标签转化后的向量。

+ **exponential——指数损失**

**二分类指数损失**
$$
L = e^{-yH(x)}
$$

**多分类指数损失**，总共有K个类别
$$
\begin{aligned}
L &=exp \left( -\frac{1}{K}\boldsymbol{y^* · H^*(x)} \right) = exp \left( -\frac{1}{K}(y^1H^1(x)+y^2H^2(x) \ + \  ... + y^kH^k(x)) \right)
\end{aligned}
$$

需要注意，指数损失中的$y^*$与交叉熵损失中的$y^*$不是同样的向量。

### 使用

#### 回归

#### 分类

### 提前停止

### 袋外估计

---
# 模型融合

## Voting

sklearn提供的API如下：

```python
# 回归问题
VotingRegressor(
    estimators, 
    *, 
    weights=None, n_jobs=None, verbose=False
)

# 分类问题
VotingClassifier(
    estimators, 
    *, 
    voting='hard', 
    weights=None, n_jobs=None, flatten_transform=True, verbose=False
)
```

### 回归问题

In [56]:
lr = LinearRegression(fit_intercept=True)

In [57]:
dtr = DecisionTreeRegressor(max_depth=5)

In [58]:
svr = SVR(kernel='rbf')

In [59]:
voting_reg = VotingRegressor(estimators=[('lr', lr), ('dtr', dtr), ('svr', svr)])

In [60]:
voting_reg.estimators

[('lr', LinearRegression()),
 ('dtr', DecisionTreeRegressor(max_depth=5)),
 ('svr', SVR())]

In [61]:
voting_reg.named_estimators

{'lr': LinearRegression(),
 'dtr': DecisionTreeRegressor(max_depth=5),
 'svr': SVR()}

In [62]:
voting_reg.fit(housing_X_train, housing_y_train)

VotingRegressor(estimators=[('lr', LinearRegression()),
                            ('dtr', DecisionTreeRegressor(max_depth=5)),
                            ('svr', SVR())])

In [63]:
voting_reg.score(housing_X_train, housing_y_train)

0.5728896678179128

In [64]:
voting_reg.score(housing_X_test, housing_y_test)

0.5657015735494171

In [65]:
voting_reg.get_params()

{'estimators': [('lr', LinearRegression()),
  ('dtr', DecisionTreeRegressor(max_depth=5)),
  ('svr', SVR())],
 'n_jobs': None,
 'verbose': False,
 'weights': None,
 'lr': LinearRegression(),
 'dtr': DecisionTreeRegressor(max_depth=5),
 'svr': SVR(),
 'lr__copy_X': True,
 'lr__fit_intercept': True,
 'lr__n_jobs': None,
 'lr__positive': False,
 'dtr__ccp_alpha': 0.0,
 'dtr__criterion': 'squared_error',
 'dtr__max_depth': 5,
 'dtr__max_features': None,
 'dtr__max_leaf_nodes': None,
 'dtr__min_impurity_decrease': 0.0,
 'dtr__min_samples_leaf': 1,
 'dtr__min_samples_split': 2,
 'dtr__min_weight_fraction_leaf': 0.0,
 'dtr__monotonic_cst': None,
 'dtr__random_state': None,
 'dtr__splitter': 'best',
 'svr__C': 1.0,
 'svr__cache_size': 200,
 'svr__coef0': 0.0,
 'svr__degree': 3,
 'svr__epsilon': 0.1,
 'svr__gamma': 'scale',
 'svr__kernel': 'rbf',
 'svr__max_iter': -1,
 'svr__shrinking': True,
 'svr__tol': 0.001,
 'svr__verbose': False}

### 分类问题

In [66]:
logis = LogisticRegression()

In [67]:
dtc = DecisionTreeClassifier(max_depth=5)

In [68]:
svc_hard = SVC(kernel='rbf')
svc_soft = SVC(kernel='rbf', probability=True)

+ **硬投票**方式

In [53]:
voting_clf = VotingClassifier(estimators=[('logis', logis), ('dtc', dtc), ('svc', svc_hard)], voting='hard')

In [54]:
voting_clf.estimators

[('logis', LogisticRegression()),
 ('dtc', DecisionTreeClassifier(max_depth=5)),
 ('svc', SVC())]

In [55]:
voting_clf.named_estimators

{'logis': LogisticRegression(),
 'dtc': DecisionTreeClassifier(max_depth=5),
 'svc': SVC()}

In [56]:
voting_clf.fit(cancer_X_train, cancer_y_train)

C:\Users\Drivi\miniconda3\envs\data-analysis\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

VotingClassifier(estimators=[('logis', LogisticRegression()),
                             ('dtc', DecisionTreeClassifier(max_depth=5)),
                             ('svc', SVC())])

In [57]:
voting_clf.score(cancer_X_train, cancer_y_train)

0.9692307692307692

In [61]:
voting_clf.get_feature_names_out()

array(['votingclassifier_logis', 'votingclassifier_dtc',
       'votingclassifier_svc'], dtype=object)

In [74]:
cancer_y_pred = voting_clf.predict(cancer_X_train)
print(cancer_y_pred.shape)

(455,)

In [75]:
cancer_y_pred[:5]

array([0, 1, 0, 0, 1])

查看每个估计器的结果，硬投票下，每个估计器是直接给出分类结果，下面有3列，每个估计器一列。

In [72]:
t1 = voting_clf.transform(cancer_X_train)
print(t1.shape)

(455, 3)

In [73]:
t1[:5]

array([[0, 0, 0],
       [1, 1, 1],
       [0, 0, 0],
       [0, 0, 0],
       [1, 1, 1]], dtype=int64)

+ **软投票**的方式

In [58]:
voting_clf_soft = VotingClassifier(estimators=[('logis', logis), ('dtc', dtc), ('svc', svc_soft)], voting='soft')

In [59]:
voting_clf_soft.fit(cancer_X_train, cancer_y_train)

C:\Users\Drivi\miniconda3\envs\data-analysis\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

VotingClassifier(estimators=[('logis', LogisticRegression()),
                             ('dtc', DecisionTreeClassifier(max_depth=5)),
                             ('svc', SVC(probability=True))],
                 voting='soft')

In [60]:
voting_clf_soft.score(cancer_X_train, cancer_y_train)

0.9758241758241758

In [84]:
cancer_y_pred_soft = voting_clf_soft.predict(cancer_X_train)

In [85]:
cancer_y_pred_soft[:5]

array([0, 1, 0, 0, 1])

In [86]:
cancer_y_pred_prob = voting_clf_soft.predict_proba(cancer_X_train)

In [87]:
cancer_y_pred_prob[:5]

array([[9.99390992e-01, 6.09008273e-04],
       [2.09467514e-01, 7.90532486e-01],
       [9.99877726e-01, 1.22274476e-04],
       [9.77141433e-01, 2.28585672e-02],
       [3.80766551e-03, 9.96192334e-01]])

查看每个估计器的结果，软投票下，**下面有6列是因为每个估计器分别给出正负两类各自的概率**。

In [96]:
t2 = voting_clf_soft.transform(cancer_X_train)
t2.shape

(455, 6)

In [83]:
t2[:5]

array([[9.99873367e-01, 1.26632846e-04, 1.00000000e+00, 0.00000000e+00,
        9.98299608e-01, 1.70039197e-03],
       [2.35197482e-01, 7.64802518e-01, 0.00000000e+00, 1.00000000e+00,
        3.93205060e-01, 6.06794940e-01],
       [9.99999928e-01, 7.19479381e-08, 1.00000000e+00, 0.00000000e+00,
        9.99633249e-01, 3.66751481e-04],
       [9.90907401e-01, 9.09259927e-03, 1.00000000e+00, 0.00000000e+00,
        9.40516898e-01, 5.94831025e-02],
       [2.20613146e-04, 9.99779387e-01, 0.00000000e+00, 1.00000000e+00,
        1.12023834e-02, 9.88797617e-01]])

正类的概率均值

In [94]:
t2[:5, [0,2,4]].mean(axis=1)

array([0.99939099, 0.20946751, 0.99987773, 0.97714143, 0.00380767])

负类的概率均值

In [95]:
t2[:5, [1,3,5]].mean(axis=1)

array([6.09008273e-04, 7.90532486e-01, 1.22274476e-04, 2.28585672e-02,
       9.96192334e-01])

---
## Stacking - KEY

有关Stacking的介绍，可以参考如下的几篇博客：
1. [模型融合方法概述](https://zhuanlan.zhihu.com/p/25836678)
2. [Kaggle机器学习之模型融合（stacking）心得](https://zhuanlan.zhihu.com/p/26890738)
3. [Introduction to Ensembling/Stacking in Python](https://www.kaggle.com/arthurtok/introduction-to-ensembling-stacking-in-python/notebook#Second-Level-Predictions-from-the-First-level-Output)

实现类详见`Stacking.py`文件。

sklearn提供的API如下：
```python
# 回归问题
StackingRegressor(
    estimators, 
    final_estimator=None, 
    *, 
    cv=None, 
    n_jobs=None, 
    passthrough=False, 
    verbose=0
)

# 分类问题
StackingClassifier(
    estimators, 
    final_estimator=None, 
    *, 
    cv=None, 
    stack_method='auto', 
    n_jobs=None, 
    passthrough=False, 
    verbose=0
)
```

**参数**：
+ `estimators`: list of `(str, estimator)`
+ `final_estimator`: 元估计器
+ `cv`: 设置用于**训练final_estimator**时交叉验证的策略，这个参数要注意一下，可选值如下：
    + `None`，使用默认的5折交叉验证
    + 整数，指定交叉验证折数
    + 可以执行cross-validation的generator
    + 分割数据集的可迭代对象
    + `prefit`: <font color='red'>这个取值要特别注意，此时表示所有的一级估计器都是训练好的，元估计器不会使用交叉验证策略，而是使用一级估计器在所有数据上的输出</font>，此时会有数据泄露的情况，非常容易出现过拟合的情况。
+ `stack_method`: 融合策略（<font color='red'>只针对`StackingClassifier`有效</font>），可选值为`{'auto', 'predict_proba', 'decision_function', 'predict'}`
    + `auto`下会对每个估计器依次尝试`predict_proba`, `decision_function`, `predict` 方法
    + 其他选项则是自己指定使用的估计器方法
+ `passthrough`: 默认`False`，表示只有一级估计器的输出会被输入到元估计器中，`True`表示则会和原始数据一起输入元估计器中。

**常用方法**：

- `transform(X)`: 输出所有**一级`estimators`的X结果**（不是预测结果），形状是`(n_samples, n_estimators)`
- `fit(X, y, **fit_params)`: 训练一级估计器和二级估计器
- `fit_transform(X, y, **fit_params)`: 等价于 `.fit(X, y).transform(X)` 的链式调用
- `predict(X, **predict_params)`: 预测 `X` 结果
- `score(X, y, sample_weight=None)`
- `get_params(deep=True)`: 以dict形式返回参数，`deep=True`时也会一并返回所有`estimators`里的参数。
- `set_params`: 设置参数，通过`get_param`返回的key，也可以**传入一级估计器的参数**。

> 顺带一提，`GridSearchCV.fit()` 方法里，也是调用 `estimator.set_params()` 方法设置参数的，也就是说可以把 `StackingClassifier` 传递给 `GridSearchCV`，并且进行 一级estimator 和 final_estimator 的超参数搜索。

### 说明

通过查看源码，Sklearn里实现的Stacking（`StackingRegressor`和`StackingClassifier`）有如下几个需要注意的点：

（1）传入的一级估计器`estimators`，都被认为是已经配置好了 **<font color='red'>超参数</font>** 的估计器，后续的 fit 中，只会对普通参数进行训练。

（2）如果`cv='prefit'`:
+ `fit`方法里不会对一级学习器进行训练（普通参数），也不会使用`cross_val_predict`获取一级学习器的OOB预测，而是直接使用每个一级学习器在整个数据集上的预测结果作为元学习器的训练数据。
+ `predict`方法里没有啥特殊处理

（3）如果`cv`取值不是`prefit`：
+ `fit`方法里首先<font color='red'>会**对每个一级学习器**使用传入的**整个数据集**训练一次模型参数（**不是超参数**）</font>。
+ 然后使用交叉预测（`cross_val_predict`）的方式得到每个一级学习器的OOB预测，作为元学习器的训练数据，但是`cross_val_predict`过程中**每折数据训练普通参数的模型不会保存**。
+ 这一意味着，<font color='red'>传入的一级学习器所使用的最优超参数需要实现我们自己实现执行一次GridSearch+CV的搜索</font>，但是这个过程会出现数据泄露的情况，导致后续使用Stacking集成时极易出现过拟合的情况。
+ `predict`方法里没有特殊处理

### 分类问题

In [28]:
RANDOM_STATE = 32
cls_estimators = [
    ("svc", SVC(kernel='rbf', random_state=RANDOM_STATE)),
    ("dct", DecisionTreeClassifier(max_depth=4, criterion='entropy', random_state=RANDOM_STATE))
]

cls_meta_estimator = LogisticRegression(random_state=RANDOM_STATE)

cls_stack_estimator = StackingClassifier(
    estimators=cls_estimators,
    final_estimator=cls_meta_estimator,
    cv=4,
    n_jobs=2,
    stack_method='auto'
)

In [30]:
cls_stack_estimator.fit(cancer_X_train, cancer_y_train)

StackingClassifier(cv=4,
                   estimators=[('svc', SVC(random_state=32)),
                               ('dct',
                                DecisionTreeClassifier(criterion='entropy',
                                                       max_depth=4,
                                                       random_state=32))],
                   final_estimator=LogisticRegression(random_state=32),
                   n_jobs=2)

In [31]:
cls_stack_estimator.score(cancer_X_train, cancer_y_train)

0.9714285714285714

In [32]:
cls_stack_estimator.score(cancer_X_test, cancer_y_test)

0.9122807017543859

In [51]:
params = cls_stack_estimator.get_params()

In [53]:
params

{'cv': 4,
 'estimators': [('svc', SVC(random_state=32)),
  ('dct',
   DecisionTreeClassifier(criterion='entropy', max_depth=4, random_state=32))],
 'final_estimator__C': 1.0,
 'final_estimator__class_weight': None,
 'final_estimator__dual': False,
 'final_estimator__fit_intercept': True,
 'final_estimator__intercept_scaling': 1,
 'final_estimator__l1_ratio': None,
 'final_estimator__max_iter': 100,
 'final_estimator__multi_class': 'deprecated',
 'final_estimator__n_jobs': None,
 'final_estimator__penalty': 'l2',
 'final_estimator__random_state': 32,
 'final_estimator__solver': 'lbfgs',
 'final_estimator__tol': 0.0001,
 'final_estimator__verbose': 0,
 'final_estimator__warm_start': False,
 'final_estimator': LogisticRegression(random_state=32),
 'n_jobs': 2,
 'passthrough': False,
 'stack_method': 'auto',
 'verbose': 0,
 'svc': SVC(random_state=32),
 'dct': DecisionTreeClassifier(criterion='entropy', max_depth=4, random_state=32),
 'svc__C': 1.0,
 'svc__break_ties': False,
 'svc__cache_size': 200,
 'svc__class_weight': None,
 'svc__coef0': 0.0,
 'svc__decision_function_shape': 'ovr',
 'svc__degree': 3,
 'svc__gamma': 'scale',
 'svc__kernel': 'rbf',
 'svc__max_iter': -1,
 'svc__probability': False,
 'svc__random_state': 32,
 'svc__shrinking': True,
 'svc__tol': 0.001,
 'svc__verbose': False,
 'dct__ccp_alpha': 0.0,
 'dct__class_weight': None,
 'dct__criterion': 'entropy',
 'dct__max_depth': 4,
 'dct__max_features': None,
 'dct__max_leaf_nodes': None,
 'dct__min_impurity_decrease': 0.0,
 'dct__min_samples_leaf': 1,
 'dct__min_samples_split': 2,
 'dct__min_weight_fraction_leaf': 0.0,
 'dct__monotonic_cst': None,
 'dct__random_state': 32,
 'dct__splitter': 'best'}

In [52]:
params.keys()

dict_keys(['cv', 'estimators', 'final_estimator__C', 'final_estimator__class_weight', 'final_estimator__dual', 'final_estimator__fit_intercept', 'final_estimator__intercept_scaling', 'final_estimator__l1_ratio', 'final_estimator__max_iter', 'final_estimator__multi_class', 'final_estimator__n_jobs', 'final_estimator__penalty', 'final_estimator__random_state', 'final_estimator__solver', 'final_estimator__tol', 'final_estimator__verbose', 'final_estimator__warm_start', 'final_estimator', 'n_jobs', 'passthrough', 'stack_method', 'verbose', 'svc', 'dct', 'svc__C', 'svc__break_ties', 'svc__cache_size', 'svc__class_weight', 'svc__coef0', 'svc__decision_function_shape', 'svc__degree', 'svc__gamma', 'svc__kernel', 'svc__max_iter', 'svc__probability', 'svc__random_state', 'svc__shrinking', 'svc__tol', 'svc__verbose', 'dct__ccp_alpha', 'dct__class_weight', 'dct__criterion', 'dct__max_depth', 'dct__max_features', 'dct__max_leaf_nodes', 'dct__min_impurity_decrease', 'dct__min_samples_leaf', 'dct__min_samples_split', 'dct__min_weight_fraction_leaf', 'dct__monotonic_cst', 'dct__random_state', 'dct__splitter'])

+ 手动设置一级基学习器的超参数，注意上面的参数中间是<font color='red'>双下划线</font>。

In [54]:
cls_stack_estimator.set_params(
    svc__C=1.2,
    dct__criterion='gini'
)

StackingClassifier(cv=4,
                   estimators=[('svc', SVC(C=1.2, random_state=32)),
                               ('dct',
                                DecisionTreeClassifier(max_depth=4,
                                                       random_state=32))],
                   final_estimator=LogisticRegression(random_state=32),
                   n_jobs=2)

In [55]:
cls_stack_estimator.get_params()

{'cv': 4,
 'estimators': [('svc', SVC(C=1.2, random_state=32)),
  ('dct', DecisionTreeClassifier(max_depth=4, random_state=32))],
 'final_estimator__C': 1.0,
 'final_estimator__class_weight': None,
 'final_estimator__dual': False,
 'final_estimator__fit_intercept': True,
 'final_estimator__intercept_scaling': 1,
 'final_estimator__l1_ratio': None,
 'final_estimator__max_iter': 100,
 'final_estimator__multi_class': 'deprecated',
 'final_estimator__n_jobs': None,
 'final_estimator__penalty': 'l2',
 'final_estimator__random_state': 32,
 'final_estimator__solver': 'lbfgs',
 'final_estimator__tol': 0.0001,
 'final_estimator__verbose': 0,
 'final_estimator__warm_start': False,
 'final_estimator': LogisticRegression(random_state=32),
 'n_jobs': 2,
 'passthrough': False,
 'stack_method': 'auto',
 'verbose': 0,
 'svc': SVC(C=1.2, random_state=32),
 'dct': DecisionTreeClassifier(max_depth=4, random_state=32),
 'svc__C': 1.2,
 'svc__break_ties': False,
 'svc__cache_size': 200,
 'svc__class_weight': None,
 'svc__coef0': 0.0,
 'svc__decision_function_shape': 'ovr',
 'svc__degree': 3,
 'svc__gamma': 'scale',
 'svc__kernel': 'rbf',
 'svc__max_iter': -1,
 'svc__probability': False,
 'svc__random_state': 32,
 'svc__shrinking': True,
 'svc__tol': 0.001,
 'svc__verbose': False,
 'dct__ccp_alpha': 0.0,
 'dct__class_weight': None,
 'dct__criterion': 'gini',
 'dct__max_depth': 4,
 'dct__max_features': None,
 'dct__max_leaf_nodes': None,
 'dct__min_impurity_decrease': 0.0,
 'dct__min_samples_leaf': 1,
 'dct__min_samples_split': 2,
 'dct__min_weight_fraction_leaf': 0.0,
 'dct__monotonic_cst': None,
 'dct__random_state': 32,
 'dct__splitter': 'best'}

### 回归问题

In [36]:
RANDOM_STATE = 32

reg_estimators = [
    ("svr", SVR(kernel='rbf')),
    ("dtr", DecisionTreeRegressor(max_depth=4, random_state=RANDOM_STATE))
]

reg_meta_estimator = LinearRegression()

reg_stack_estimator = StackingRegressor(
    estimators=reg_estimators,
    final_estimator=reg_meta_estimator,
    cv=4
)

In [46]:
reg_stack_estimator.fit(housing_X_train, housing_y_train)

StackingRegressor(cv=4,
                  estimators=[('svr', SVR()),
                              ('dtr',
                               DecisionTreeRegressor(max_depth=4,
                                                     random_state=32))],
                  final_estimator=LinearRegression())

In [47]:
reg_stack_estimator.score(housing_X_train, housing_y_train)

0.5932594142154739

In [48]:
reg_stack_estimator.score(housing_X_test, housing_y_test)

0.5853404525788372

In [49]:
reg_stack_estimator.get_params()

{'cv': 4,
 'estimators': [('svr', SVR()),
  ('dtr', DecisionTreeRegressor(max_depth=4, random_state=32))],
 'final_estimator__copy_X': True,
 'final_estimator__fit_intercept': True,
 'final_estimator__n_jobs': None,
 'final_estimator__positive': False,
 'final_estimator': LinearRegression(),
 'n_jobs': None,
 'passthrough': False,
 'verbose': 0,
 'svr': SVR(),
 'dtr': DecisionTreeRegressor(max_depth=4, random_state=32),
 'svr__C': 1.0,
 'svr__cache_size': 200,
 'svr__coef0': 0.0,
 'svr__degree': 3,
 'svr__epsilon': 0.1,
 'svr__gamma': 'scale',
 'svr__kernel': 'rbf',
 'svr__max_iter': -1,
 'svr__shrinking': True,
 'svr__tol': 0.001,
 'svr__verbose': False,
 'dtr__ccp_alpha': 0.0,
 'dtr__criterion': 'squared_error',
 'dtr__max_depth': 4,
 'dtr__max_features': None,
 'dtr__max_leaf_nodes': None,
 'dtr__min_impurity_decrease': 0.0,
 'dtr__min_samples_leaf': 1,
 'dtr__min_samples_split': 2,
 'dtr__min_weight_fraction_leaf': 0.0,
 'dtr__monotonic_cst': None,
 'dtr__random_state': 32,
 'dtr__splitter': 'best'}

----
# 其他

## IsolationForest
孤立森林异常检测算法。

```python
IsolationForest(
    *, n_estimators=100, 
    max_samples='auto', contamination='auto', 
    max_features=1.0, bootstrap=False, 
    n_jobs=None, random_state=None, verbose=0, warm_start=False
)
```